// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordStore.DAL.Context;

#nullable disable

namespace RecordStore.DAL.Migrations
{
    [DbContext(typeof(RecordStoreDbContext))]
    [Migration("20241027175353_AddedNewSeedDatas")]
    partial class AddedNewSeedDatas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecordStore.DAL.Entities.Concrete.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(7,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateOnly>("PublishedDate")
                        .HasColumnType("date");

                    b.Property<string>("Singers")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Album", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 11, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 0.78m,
                            IsActive = true,
                            Name = "AM",
                            Price = 100m,
                            PublishedDate = new DateOnly(2013, 8, 12),
                            Singers = "Arctic Monkeys"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 9, 11, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 0.5m,
                            IsActive = true,
                            Name = "Favourite Worst Nightmare",
                            Price = 200m,
                            PublishedDate = new DateOnly(2007, 10, 3),
                            Singers = "Arctic Monkeys"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 8, 11, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 0.76m,
                            IsActive = true,
                            Name = "Biraz Pop Biraz Sezen",
                            Price = 300m,
                            PublishedDate = new DateOnly(2017, 2, 17),
                            Singers = "Sezen Aksu"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 7, 11, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 0.76m,
                            IsActive = false,
                            Name = "Please Please Me",
                            Price = 750m,
                            PublishedDate = new DateOnly(1963, 7, 11),
                            Singers = "The Beatles"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 6, 11, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 1m,
                            IsActive = true,
                            Name = "CryBaby",
                            Price = 500m,
                            PublishedDate = new DateOnly(2016, 6, 18),
                            Singers = "Lil Peep"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 5, 11, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 0.89m,
                            IsActive = true,
                            Name = "Astroworld",
                            Price = 625m,
                            PublishedDate = new DateOnly(2023, 5, 21),
                            Singers = "Travis Scott"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 4, 11, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 0.78m,
                            IsActive = false,
                            Name = "Bak Kollarım Burada",
                            Price = 310m,
                            PublishedDate = new DateOnly(2019, 4, 5),
                            Singers = "Mert Demir"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 3, 11, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 0.93m,
                            IsActive = true,
                            Name = "Homecoming",
                            Price = 900m,
                            PublishedDate = new DateOnly(2019, 9, 7),
                            Singers = "Beyonce"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 2, 11, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 0.95m,
                            IsActive = false,
                            Name = "Yolcu",
                            Price = 95m,
                            PublishedDate = new DateOnly(2003, 5, 13),
                            Singers = "Neşet Ertaş"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 1, 11, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 0.85m,
                            IsActive = true,
                            Name = "Seni Kendime Sakladım",
                            Price = 175m,
                            PublishedDate = new DateOnly(2004, 5, 19),
                            Singers = "Duman"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 6, 10, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 0.7m,
                            IsActive = true,
                            Name = "Antichrist Superstar",
                            Price = 700m,
                            PublishedDate = new DateOnly(1996, 10, 8),
                            Singers = "Marilyn Manson"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 6, 9, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 0.65m,
                            IsActive = true,
                            Name = "Hal Hal",
                            Price = 585m,
                            PublishedDate = new DateOnly(1989, 11, 22),
                            Singers = "Barış Manço"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 10, 11, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 1m,
                            IsActive = false,
                            Name = "In Utero",
                            Price = 100m,
                            PublishedDate = new DateOnly(1993, 9, 21),
                            Singers = "Nirvana"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 10, 11, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 0.65m,
                            IsActive = true,
                            Name = "Büyük İnsan",
                            Price = 320m,
                            PublishedDate = new DateOnly(2010, 7, 16),
                            Singers = "Gökhan Türkmen"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 10, 11, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 0.93m,
                            IsActive = false,
                            Name = "Resimdeki Gözyaşları",
                            Price = 700m,
                            PublishedDate = new DateOnly(1968, 8, 10),
                            Singers = "Cem Karaca"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 10, 11, 11, 43, 11, 412, DateTimeKind.Local).AddTicks(5286),
                            Discount = 0.84m,
                            IsActive = true,
                            Name = "Dünden Yarına",
                            Price = 560m,
                            PublishedDate = new DateOnly(1988, 3, 17),
                            Singers = "İlhan İrem'"
                        });
                });

            modelBuilder.Entity("RecordStore.DAL.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("User", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Password = "1c878f9f7033734c34647bfd6bb1e312dd835f319b3df608873444f3a9e65769",
                            UserName = "Samet"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Password = "45e01a38ba96519d7ad13fbf9cb03442768c9f3f2d4c69143554670e54d3f18b",
                            UserName = "Meltem"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Password = "428b5b31f6f928e466cba5926691b5b18b9dea5d8243114d27cb2909464f22d7",
                            UserName = "Batuhan"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Password = "504d3d0e64bef294ad0e15b86f8813bc6ea3b20cd70787b98d47aadba7d98d0d",
                            UserName = "Aydan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
